name: Run Postman Tests with Newman

on:
  push:
    branches:
      - main

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman and htmlextra Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Collection
        run: |
          newman run "api-collection/jsonplaceholder_postman_collection.json" \
            --environment "postman-environment/jsonplaceholder_env.json" \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export "reports/htmlreport.html"

      - name: Upload HTML Report
        uses: ac
